name: project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  grouped_list: ^6.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins-regular
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
    - family: Poppins-bold
      fonts:
        - asset: assets/font/Poppins/Poppins-Bold.ttf
    - family: Gotham-regular
      fonts:
        - asset: assets/font/Gotham/GothamLight.ttf
    - family: Gotham-regular
      fonts:
        - asset: assets/font/Gotham/GothamMedium.ttf
    - family: Gotham-bold
      fonts:
        - asset: assets/font/Gotham/GothamBold.ttf
